services:
  mysql:
    image: mysql:oracle
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: jsb
      MYSQL_ROOT_PASSWORD: hieuhoang222
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - jsb
networks:
  jsb:
    name: jsb